### ISSUE TITLE
instalasi

### ISSUE THREAD

**Issue by parma03** [salmanagustian/wedding-digital-invitation#1]
instalasinya gmana pak?

**Comment by salmanagustian** [comment]
1. clone repo wedding-digital-invitation
2. run command composer install/composer update di cmd/git bash
3. buat file dengan ekstensi .env, lalu run command php artisan key:generate
4. setting .env sesuaikan dengan settingan database di lokal kamu
5. run command npm run dev (untuk menjalankan compile file vue js)

kira2 seperti itu pak :)

untuk stuktur tabel nya kira2 seperti ini
![Capture](https://user-images.githubusercontent.com/27839071/167323640-a0971190-0977-4ec5-9029-9f57cad39af0.JPG)

**Comment by parma03** [comment]
eror pas di npm install & run devnya pak
npm install
```
added 1030 packages, and audited 1031 packages in 23s

92 packages are looking for funding
  run `npm fund` for details

16 vulnerabilities (8 moderate, 7 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```
npm run dev
```
ERROR in ./resources/js/views/Home.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??clonedRuleSet-5[0].rules[0].use[0]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./resources/js/views/Home.vue?vue&type=script&lang=js&) 177:0-51
Module not found: Error: Can't resolve 'vue-infinite-loading' in 'C:\xampp\htdocs\wedding-digital-invitation\resources\js\views'

webpack compiled with 1 error
```

**Comment by salmanagustian** [comment]
itu tinggal di install package vue-infine-loading nya aja pak.

Bisa run command sprt berikut: npm install vue-infinite-loading.
