### ISSUE TITLE
instalasi

### ISSUE THREAD

**Issue by ojidesigner** [salmanagustian/wedding-digital-invitation#2]
masih bingung instalasinya kak? bisa dijelaskan lebih detail kak, maaf aku pemula

**Comment by salmanagustian** [comment]
besok siang coba saya update ya untuk proses instalasi nya di .readme :)

**Comment by ojidesigner** [comment]
Oke siap kak

**Comment by ojidesigner** [comment]
Oke kak ditunggu

**Comment by salmanagustian** [comment]
cara instalasi nya udh diupdate di readme.md repo ini ya :)

**Comment by ojidesigner** [comment]
Oke kak terima kasih, untuk di localhost Alhamdulillah udh bisa kak, tapi untuk saya upload ke C-Panel belum bisa, bnyak fitur yg ngga berfungsi, coba cek kak https://putri.oji.my.id

**Comment by salmanagustian** [comment]
Mantapps! :)

Yang ane bisa review:
1. font nya gak ke baca (font header section)
2. foto mempelai sama gak ke baca

btw. Url website wedding nya ane taro di showcast project repo ini gpp?

**Comment by ojidesigner** [comment]
Iya gpp kak, oh ya kak, cara mengatasi nya gmna ? Untuk font & fotonya

**Comment by salmanagustian** [comment]
path atau url lokasi foto dan font nya bisa di cek lagi kak :) disamakan dengan apa yg dibutuhin sama file nya

**Comment by salmanagustian** [comment]
closed.
